version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    ports:
      - "1433:1433"
    networks:
      - app-network
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: Password1
    volumes:
      - mssql-data:/var/opt/mssql
      - ./mssql-init:/docker-entrypoint-initdb.d
networks:
  app-network:
volumes:
  mssql-data:
